FORMAT: 1A
HOST: http://private-225f59-sniper1.apiary-mock.com/

# Snipe

Snipe is an API backend for the Snipe Marketplace

## Authentication [/auth]

### Register [POST /auth/register] 

+ Request (application/json)

        {
            "firstname": "John",
            "lastname": "Doe",
            "phonenumber": "+2348077788899",
            "email": "john@doe.com",
            "password": "theSafePa$$w0rd$$555//"
        }

+ Response 200 (application/json)
        
        {
            "status": "success",
            "data": {
                "firstname": "John",
                "lastname": "Doe",
                "phonenumber": "+2348077788899",
                "email": "john@doe.com"
            }
        }
        
### Reset Password [POST /auth/resetpassword]

+ Request (application/json)

        {
            "email": "john@doe.com",
            "oldPassword": "theSafePa$$w0rd$$555//", // (optional)
            "password": "theSafePa$$w0rd$$555//",
            "confirmPassword": "theSafePa$$w0rd$$555//"
        }

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "message": "Verification email sent. or Password changed."
            }
        }
        
### Verify Password Reset [GET /auth/verifyresetpassword/:hash]
Do html redirect to the password reset successful page

+ Parameters
    + hash: "2d3343ae567c8f8a0b9e8f" (string, required) - verification hash from password reset verification email.

+ Response 200 (text/html)
        
### Log In [POST]

+ Request (application/json)

        {
            "email": "john@doe.com",
            "password": "theSafePa$$w0rd$$555//",
        }

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "accessToken": "2d3343ae567c8f8a0b9e8f2d3343ae567c8f8a0b9e8f",
                "expiry": "3600",
                "refreshToken": "3d3343ae567c8f8a0b9e8f2d3343ae567c8f8a0b9e8f",
                "x-tag": "3d3343ae567c8f8a0b9e8f2d3343ae567c8f8a0b9e8f/=="
            }
        }
        
### Log Out [GET /auth/logout]
Note: Do html redirect to the password reset successful page and kill the active access token and refresh tokens


+ Response 200 (text/html)
        
### Deactivate [GET /auth/deactivate/:user_id]

+ Parameter
    + user_id: "2d3343ae567c8f8a0b9e8f" (String, required) - The id of the user to be deactivated

Finished + Headers
    Authorization: dd3343ae567c8f8a0b9e8f // This token must be of an administrator or the user to be deactivated

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "message": "User deactivated."
            }
        }

## User Management [/users]

### View Users [GET]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                [
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "firstname": "John",
                        "lastname": "Doe",
                        "addressBook": [{
                            "phonenumber": "+2348077788899",
                            "email": "john@doe.com"
                        }]
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "firstname": "John",
                        "lastname": "Doe",
                        "addressBook": [{
                            "phonenumber": "+2348077788899",
                            "email": "john@doe.com"
                        }]
                    }
                ]
            }
        }
        
### View User [GET /users/:user_id]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 

+ Parameters
    + user_id: "2d3343ae567c8f8a0b9e8f" (String, required) - The id of the user

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "firstname": "John",
                "lastname": "Doe",
                "addressBook": [{
                    "phonenumber": "+2348077788899",
                    "email": "john@doe.com"
                }]
            }
        }
    
### Update User [PUT /users/:user_id]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 

+ Parameters
    + user_id: "2d3343ae567c8f8a0b9e8f" (String, required) - The id of the user
    + limit: "10" (Number) - Number of records to return
    + skip: "0" (Number)  - Number of records to skip

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "firstname": "John",
                "lastname": "Doe",
                "addressBook": [{
                    "phonenumber": "+2348077788899",
                    "email": "john@doe.com"
                }],
                "products": {
                    "item":"price",
                    "item2":"price",
                    "item3":"price",
                    "item4":"price",
                }
            }
        }
        
### Filter Users [GET]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 

+ Parameters
    + limit: "10" (Number) - Number of records to return
    + skip: "0" (Number)  - Number of records to skip
    + email: "foo@joo.com" (String)  - Email of the user
    + firstname: "Foo" (String)  - First name of the user
    + lastname: "John" (String)  - Last name of the user
    + rangeFrom: "2017-03-01" (Date)  - Date range start
    + rangeTo: "2017-03-15" (Date)  - Date range end

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                [
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "firstname": "John",
                        "lastname": "Doe",
                        "addressBook": [{
                            "phonenumber": "+2348077788899",
                            "email": "john@doe.com"
                        }]
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "firstname": "John",
                        "lastname": "Doe",
                        "addressBook": [{
                            "phonenumber": "+2348077788899",
                            "email": "john@doe.com"
                        }]
                    }
                ]
            }
        }
        
### Export Users [GET /users/export]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 

+ Parameters
    + limit: "10" (Number) - Number of records to return
    + skip: "0" (Number)  - Number of records to skip
    + email: "foo@joo.com" (String)  - Email of the user
    + firstname: "Foo" (String)  - First name of the user
    + lastname: "John" (String)  - Last name of the user
    + rangeFrom: "2017-03-01" (Date)  - Date range start
    + rangeTo: "2017-03-15" (Date)  - Date range end

+ Response 200 (text/csv)
        
### Invite Friends [GET /users/invite]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 
    
+ Request (application/json)

        [
            {
                "email": "john@doe.com"
            },
            {
                "email": "john2@doe.com"
            }
        ]

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "message": "Invitation sent."
            }
        }
        
## File Management [/files]
        
### View User Files [GET /files/:user_id]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 

+ Parameters
    + user_id: "2d3343ae567c8f8a0b9e8f" (String, required) - The id of the user
    + limit: "10" (Number) - Number of records to return
    + skip: "0" (Number)  - Number of records to skip

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                [
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "url": "https://foo.com/asset.png"
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "url": "https://foo.com/asset.png"
                    }
                ]
            }
        }
        
### View User File [GET /files/:user_id/:file_id]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 

+ Parameters
    + user_id: "2d3343ae567c8f8a0b9e8f" (String, required) - The id of the user
    + file_id: "5d3343ae567c8f8a0b9e8f" (String, required) - The id of the file

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "url": "https://foo.com/asset.png"
            }
        }
        
### View File [GET /files/:user_id/:file_id/file]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 

+ Parameters
    + user_id: "2d3343ae567c8f8a0b9e8f" (String, required) - The id of the user
    + file_id: "5d3343ae567c8f8a0b9e8f" (String, required) - The id of the file

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "url": "https://foo.com/asset.png"
            }
        }
        
### View Files [GET]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 

+ Parameters
    + limit: "10" (Number) - Number of records to return
    + skip: "0" (Number)  - Number of records to skip

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                [
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "url": "https://foo.com/asset.png"
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "url": "https://foo.com/asset.png"
                    }
                ]
            }
        }
        
### Add User File [POST]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 

+ Request (application/json)

        {
            "url": "https://foo.com/asset.png"
        }

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "url": "https://foo.com/asset.png"
            }
        }
        
### Update User File [PUT /files/:file_id]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 

+ Parameters
    + file_id: "5d3343ae567c8f8a0b9e8f" (String, required) - The id of the file

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "url": "https://foo.com/asset.png"
            }
        }
        
## Notifications [/notifications]
        
### View Notifications [GET]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 
    
+ Parameters
    + limit: "10" (Number) - Number of records to return
    + skip: "0" (Number)  - Number of records to skip

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                [
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "content": "This is a message",
                        "destination": "fio@yahoo.com",
                        "type": "email",
                        "is_opened": true
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "content": "this is another message",
                        "destination": "3456789876533",
                        "type": "push",
                        "is_opened": false
                    }
                ]
            }
        }
        
### View Notification [GET /notifications/:notification_id]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 
    
+ Parameters
    + notification_id: "10" (Number) - ID if notification to return

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "content": "This is a message",
                "destination": "fio@yahoo.com",
                "type": "email",
                "is_opened": true
            }
        }
        
## Bookings [/bookings]

### View Bookings [GET]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 
    
+ Parameters
    + limit: "10" (Number) - Number of records to return
    + skip: "0" (Number)  - Number of records to skip

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                [
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "amount": 2000,
                        "data": {
                            "kitchen": 1,
                            "livingRoom": 1,
                            "bedroom": 3,
                            "bathroom": 1,
                            "cupboard": 1
                        },
                        "statu": "pending",
                        "payments": [
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "completed",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            },
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "pending",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            }
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "processing",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            }
                        ]
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "amount": 2000,
                        "data": {
                            "kitchen": 1,
                            "livingRoom": 1,
                            "bedroom": 3,
                            "bathroom": 1,
                            "cupboard": 1
                        },
                        "statu": "completed",
                        "payments": [
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "completed",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            },
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "pending",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            }
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "processing",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            }
                        ]
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "amount": 2000,
                        "data": {
                            "kitchen": 1,
                            "livingRoom": 1,
                            "bedroom": 3,
                            "bathroom": 1,
                            "cupboard": 1
                        },
                        "statu": "canceled",
                        "payments": [
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "completed",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            },
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "pending",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            }
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "processing",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            }
                        ]
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "amount": 2000,
                        "data": {
                            "kitchen": 1,
                            "livingRoom": 1,
                            "bedroom": 3,
                            "bathroom": 1,
                            "cupboard": 1
                        },
                        "statu": "ongoing",
                        "payments": [
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "completed",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            },
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "pending",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            }
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "processing",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            }
                        ]
                    }
                ]
            }
        }
            
### View Booking [GET /bookings/:booking_id]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 
    
+ Parameters
    + booking_id: "10" (Number) - ID of booking to return

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "amount": 2000,
                "data": {
                    "kitchen": 1,
                    "livingRoom": 1,
                    "bedroom": 3,
                    "bathroom": 1,
                    "cupboard": 1
                },
                "statu": "ongoing",
                "payments": [
                    {
                        "user_id": "2d3343ae567c8f8a0b9e8f",
                        "amount": 2000,
                        "fee": 20,
                        "providerFee": 10,
                        "status": "completed",
                        "provider_response": {
                            "statusCode": "00",
                            "message": "successful"
                        }
                    },
                    {
                        "user_id": "2d3343ae567c8f8a0b9e8f",
                        "amount": 2000,
                        "fee": 20,
                        "providerFee": 10,
                        "status": "pending",
                        "provider_response": {
                            "statusCode": "00",
                            "message": "successful"
                        }
                    }
                    {
                        "user_id": "2d3343ae567c8f8a0b9e8f",
                        "amount": 2000,
                        "fee": 20,
                        "providerFee": 10,
                        "status": "processing",
                        "provider_response": {
                            "statusCode": "00",
                            "message": "successful"
                        }
                    }
                ]
            }
        }
        
### Complete Booking [POST /bookings/:booking_id/complete]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 
    
+ Parameters
    + booking_id: "10" (Number) - ID of booking to return

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "message":"Booking Completed"
            }
        }
        
### Cancel Booking [POST /bookings/:booking_id/cancel]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 
    
+ Parameters
    + booking_id: "10" (Number) - ID of booking to return

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "message":"Booking Canceled"
            }
        }
        
### Filter Bookings [GET]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 
    
+ Parameters
    + limit: "10" (Number) - Number of records to return
    + skip: "0" (Number)  - Number of records to skip
    + amount: 2000 (String)  - Amount of a booking
    + status: "completed" (String)  - Status of a booking
    + id: "f2dd3343ae567c8f8a0b9e8f" (String)  - ID of a booking
    + rangeFrom: "2017-03-01" (Date)  - Date range start
    + rangeTo: "2017-03-15" (Date)  - Date range end

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                [
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "amount": 2000,
                        "data": {
                            "kitchen": 1,
                            "livingRoom": 1,
                            "bedroom": 3,
                            "bathroom": 1,
                            "cupboard": 1
                        },
                        "statu": "pending",
                        "payments": [
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "completed",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            },
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "pending",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            }
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "processing",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            }
                        ]
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "amount": 2000,
                        "data": {
                            "kitchen": 1,
                            "livingRoom": 1,
                            "bedroom": 3,
                            "bathroom": 1,
                            "cupboard": 1
                        },
                        "statu": "completed",
                        "payments": [
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "completed",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            },
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "pending",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            }
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "processing",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            }
                        ]
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "amount": 2000,
                        "data": {
                            "kitchen": 1,
                            "livingRoom": 1,
                            "bedroom": 3,
                            "bathroom": 1,
                            "cupboard": 1
                        },
                        "statu": "canceled",
                        "payments": [
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "completed",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            },
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "pending",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            }
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "processing",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            }
                        ]
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "amount": 2000,
                        "data": {
                            "kitchen": 1,
                            "livingRoom": 1,
                            "bedroom": 3,
                            "bathroom": 1,
                            "cupboard": 1
                        },
                        "statu": "ongoing",
                        "payments": [
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "completed",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            },
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "pending",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            }
                            {
                                "user_id": "2d3343ae567c8f8a0b9e8f",
                                "amount": 2000,
                                "fee": 20,
                                "providerFee": 10,
                                "status": "processing",
                                "provider_response": {
                                    "statusCode": "00",
                                    "message": "successful"
                                }
                            }
                        ]
                    }
                ]
            }
        }
        
### New Booking [POST]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 
    
+ Request (application/json)

        {
            "amount": 2000,
            "data": {
                "kitchen": 1,
                "livingRoom": 1,
                "bedroom": 3,
                "bathroom": 1,
                "cupboard": 1
            }
        }

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "amount": 2000,
                "data": {
                    "kitchen": 1,
                    "livingRoom": 1,
                    "bedroom": 3,
                    "bathroom": 1,
                    "cupboard": 1
                },
                "statu": "pending",
                "payments": []
            }
        }
        
### Copy Booking [POST /bookings/:booking_id/copy]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "amount": 2000,
                "data": {
                    "kitchen": 1,
                    "livingRoom": 1,
                    "bedroom": 3,
                    "bathroom": 1,
                    "cupboard": 1
                },
                "status": "pending",
                "payments": []
            }
        }
        
### Stop Booking Reminder [POST /bookings/:booking_id/stopreminder]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "message": "Reminder disabled for this booking"
            }
        }
        
### Assign Worker to Booking [POST /bookings/:booking_id/assign]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f
    
+ Request (application/json)

        {
            "worker_id": dd3343ae567c8f8a0b9e8f
        }

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "data": {
                    "kitchen": 1,
                    "livingRoom": 1,
                    "bedroom": 3,
                    "bathroom": 1,
                    "cupboard": 1
                },
                "status": "ongoing",
                "payments": [],
                "assignedTo": [{
                    "id": "2d3343ae567c8f8a0b9e8f", 
                    "firstname": "John",
                    "lastname": "Doe",
                    "addressBook": [{
                        "phonenumber": "+2348077788899",
                        "email": "john@doe.com"
                    }]
                }]
            }
        }
        
### Export Bookings [GET]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 
    
+ Parameters
    + limit: "10" (Number) - Number of records to return
    + skip: "0" (Number)  - Number of records to skip
    + amount: 2000 (String)  - Amount of a booking
    + status: "completed" (String)  - Status of a booking
    + id: "f2dd3343ae567c8f8a0b9e8f" (String)  - ID of a booking
    + rangeFrom: "2017-03-01" (Date)  - Date range start
    + rangeTo: "2017-03-15" (Date)  - Date range end

+ Response 200 (text/csv)
        
### Recommend Worker for a Booking [GET /booking/:booking_id/recommendworker]
Check if the Worker is close to the state and LGA of the booking, then arrange the workers by rating. High rating first

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 
    
+ Parameters
    + limit: "10" (Number) - Number of records to return
    + skip: "0" (Number)  - Number of records to skip
    + booking_id (Number)  - ID of the booking
    
+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                [
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "firstname": "John",
                        "lastname": "Doe",
                        "addressBook": [{
                            "phonenumber": "+2348077788899",
                            "email": "john@doe.com"
                        }]
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "firstname": "John",
                        "lastname": "Doe",
                        "addressBook": [{
                            "phonenumber": "+2348077788899",
                            "email": "john@doe.com"
                        }]
                    }
                ]
            }
        }
        
### Get Customer Details for a Booking [GET /booking/:booking_id/customerdetails]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 
    
+ Parameters
    + booking_id (Number)  - ID of the booking

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "firstname": "John",
                "lastname": "Doe",
                "addressBook": [{
                    "phonenumber": "+2348077788899",
                    "email": "john@doe.com"
                }]
            }
        }
        
### Get Workers Details for a Booking [GET /booking/:booking_id/workersdetails]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 
    
+ Parameters
    + booking_id (Number)  - ID of the booking

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                [
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "firstname": "John",
                        "lastname": "Doe",
                        "addressBook": [{
                            "phonenumber": "+2348077788899",
                            "email": "john@doe.com"
                        }]
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "firstname": "John",
                        "lastname": "Doe",
                        "addressBook": [{
                            "phonenumber": "+2348077788899",
                            "email": "john@doe.com"
                        }]
                    }
                ]
            }
        }
        
### Rate and Write a Review for a Booking [POST /booking/:booking_id/review]
Add the rating and review to each worker assigned to the project

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 
    
+ Parameters
    + booking_id (Number)  - ID of the booking
    
+ Request (application/json)
    
    {
        "rating": 5,
        "review": "This is a review for this good service"
    }

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "message": "Review has been added successful."
            }
        }
        
### Pay Worker for Bookings [POST /booking/:booking_id/payworker]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f 
    
+ Parameters
    + booking_id (Number)  - ID of the booking

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "message": "Review has been added successful.",
                "amountPaid": 5000
            }
        }
        
## Payments [/payments]

### Initiate Payment for a Booking [POST]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f

+ Request (application/json)

        {
            "booking_id": "dd3343ae567c8f8a0b9e8f",
            "amount": 4000
        }

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "booking_id": "dd3343ae567c8f8a0b9e8f",
                "amount": 4000,
                "user_id": "dd3343ae567c8f8a0b9e8f",
                "fee": 20,
                "status": "pending",
                "provider_response": {}
            }
        }

### Complete Payment for a Booking [POST /payments/:payment_id/complete]
Remember to requery the transaction to confirm the true state from the processor

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f

+ Parameters
    + payment_id (Number)  - ID of the payment

+ Request (application/json)

        {
            "status": "completed or failed"
        }

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "booking_id": "dd3343ae567c8f8a0b9e8f",
                "amount": 4000,
                "user_id": "dd3343ae567c8f8a0b9e8f",
                "fee": 20,
                "status": "completed",
                "provider_response": {}
            }
        }
### View users payments [GET /payments]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f

+ Parameters
    + user_id (Number)  - ID of the user
    + limit: "10" (Number) - Number of records to return
    + skip: "0" (Number)  - Number of records to skip
    + status: "completed" (String)  - Status of a booking
    + rangeFrom: "2017-03-01" (Date)  - Date range start
    + rangeTo: "2017-03-15" (Date)  - Date range end

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                [{
                    "id": "2d3343ae567c8f8a0b9e8f", 
                    "booking_id": "dd3343ae567c8f8a0b9e8f",
                    "amount": 4000,
                    "user_id": "dd3343ae567c8f8a0b9e8f",
                    "fee": 20,
                    "status": "completed",
                    "provider_response": {}
                },
                {
                    "id": "2d3343ae567c8f8a0b9e8f", 
                    "booking_id": "dd3343ae567c8f8a0b9e8f",
                    "amount": 4000,
                    "user_id": "dd3343ae567c8f8a0b9e8f",
                    "fee": 20,
                    "status": "pending",
                    "provider_response": {}
                }]
            }
        }
        
## Reporting [/reporting]
        
### View Report [GET]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f
    
+ Parameters
    + duration "weekly" (String)  - duration of report
    + type "customers or transactions or workers" (String)  - Type of report
    + date "2017-03-04" (Date)  - Reporting date

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                [{
                    "id": "2d3343ae567c8f8a0b9e8f", 
                    "generateddate": "2017-03-02",
                    "value": 4000,
                    "volume": 20,
                    "revenue": 20,
                    "customername": "Akpan Uche", // Optional
                    "workername": "Ngozi Emeka" // Optional
                },
                {
                    "id": "2d3343ae567c8f8a0b9e8f", 
                    "generateddate": "2017-03-02",
                    "value": 4000,
                    "volume": 20,
                    "revenue": 20,
                    "customername": "Akpan Uche", // Optional
                    "workername": "Ngozi Emeka" // Optional
                },
                {
                    "id": "2d3343ae567c8f8a0b9e8f", 
                    "generateddate": "2017-03-02",
                    "value": 4000,
                    "volume": 20,
                    "revenue": 20,
                    "customername": "Akpan Uche", // Optional
                    "workername": "Ngozi Emeka" // Optional
                },
                {
                    "id": "2d3343ae567c8f8a0b9e8f", 
                    "generateddate": "2017-03-02",
                    "value": 4000,
                    "volume": 20,
                    "revenue": 20,
                    "customername": "Akpan Uche", // Optional
                    "workername": "Ngozi Emeka" // Optional
                }]
            }
        }
        
## Collaboration [/collaboration]
        
### Invite Team Member [GET]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f

+ Request (application/json)

        {
            "firstname": "John",
            "lastname": "Doe",
            "phonenumber": "+2348077788899",
            "email": "john@doe.com",
            "password": "theSafePa$$w0rd$$555//",
            "role_id": "2d3343ae567c8f8a0b9e8f"
        }

+ Response 200 (application/json)
        
        {
            "status": "success",
            "data": {
                "firstname": "John",
                "lastname": "Doe",
                "phonenumber": "+2348077788899",
                "email": "john@doe.com",
                "passwordReset": true
            }
        }
        
## Access Management [/roles]
        
### View Roles [GET]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f
    
+ Parameters
    + limit: "10" (Number) - Number of records to return
    + skip: "0" (Number)  - Number of records to skip

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                [{
                    "id": "2d3343ae567c8f8a0b9e8f", 
                    "rolename": "Admin",
                    "permisions": [{
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "model": "User",
                        "read": true,
                        "update": false,
                        "create": true,
                        "delete": false
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "model": "Authentication",
                        "read": true,
                        "update": false,
                        "create": true,
                        "delete": false
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "model": "Transactions",
                        "read": true,
                        "update": false,
                        "create": true,
                        "delete": false
                    }]
                },
                {
                    "id": "2d3343ae567c8f8a0b9e8f", 
                    "rolename": "Public",
                    "permisions": [{
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "model": "User",
                        "read": true,
                        "update": false,
                        "create": true,
                        "delete": false
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "model": "Authentication",
                        "read": true,
                        "update": false,
                        "create": true,
                        "delete": false
                    },
                    {
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "model": "Transactions",
                        "read": true,
                        "update": false,
                        "create": true,
                        "delete": false
                    }]
                }]
            }
        }
        
### Assign Role [POST /roles/:role_id/assign]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f
    
+ Parameters
    + role_id: "10" (Number) - The ID of the role to assign

+ Request (application/json)

        [{
            "user_id": "dd3343ae567c8f8a0b9e8fd"
        },
        {
            "user_id": "e4d3343ae567c8f8a0b9e8f"
        }]

+ Response 200 (application/json)

        {
            "status": "success",
            "data": [{
                "id": "2d3343ae567c8f8a0b9e8f", 
                "firstname": "John",
                "lastname": "Doe",
                "addressBook": [{
                    "phonenumber": "+2348077788899",
                    "email": "john@doe.com"
                }],
                "role_id": "2d3343ae567c8f8a0b9e8f"
            }]
        }
        
### View Role [GET /roles/:role_id]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f
    
+ Parameters
    + role_id: "10" (Number) - The ID of the role

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "rolename": "Admin",
                "permisions": []
            }
        }
        
### Update Role [PUT /roles/:role_id]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f
    
+ Parameters
    + role_id: "10" (Number) - The ID of the role
    
+ Request (application/json)

        {
            "rolename": "SomeOtherName"
        }

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "rolename": "Admin",
                "permisions": []
            }
        }
        
### Add Permissions to Role [POST /roles/:role_id/addpermission]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f
    
+ Parameters
    + role_id: "10" (Number) - The ID of the role
    
+ Request (application/json)
        { 
            "model": "Transactions",
            "read": true,
            "update": false,
            "create": true,
            "delete": false
        }

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "rolename": "Admin",
                "permisions": [{
                    "id": "2d3343ae567c8f8a0b9e8f", 
                    "rolename": "Public",
                    "permisions": [{
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "model": "User",
                        "read": true,
                        "update": false,
                        "create": true,
                        "delete": false
                    }]
                }]
            }
        }
        
### Update Permissions on Role [PUT /roles/:role_id/updatepermission/:permission_id]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f
    
+ Parameters
    + role_id: "10" (Number) - The ID of the role
    + permission_id: "20" (Number) - The ID of the permission to update
    
+ Request (application/json)
        { 
            "model": "Transactions",
            "read": true,
            "update": false,
            "create": true,
            "delete": false
        }

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "rolename": "Admin",
                "permisions": [{
                    "id": "2d3343ae567c8f8a0b9e8f", 
                    "rolename": "Public",
                    "permisions": [{
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "model": "User",
                        "read": true,
                        "update": false,
                        "create": true,
                        "delete": false
                    }]
                }]
            }
        }
        
### Remove Permissions From Role [DELETE /roles/:role_id/deletepermission/:permission_id]

+ Headers
    Authorization: dd3343ae567c8f8a0b9e8f
    
+ Parameters
    + role_id: "10" (Number) - The ID of the role
    + permission_id: "20" (Number) - The ID of the permission to update

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "2d3343ae567c8f8a0b9e8f", 
                "rolename": "Admin",
                "permisions": [{
                    "id": "2d3343ae567c8f8a0b9e8f", 
                    "rolename": "Public",
                    "permisions": [{
                        "id": "2d3343ae567c8f8a0b9e8f", 
                        "model": "User",
                        "read": true,
                        "update": false,
                        "create": true,
                        "delete": false
                    }]
                }]
            }
        }
        
## Payment Page [/pay]
        
### Payment Page [GET /pay/:alias]

+ Response 200 (text/html)